# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 06:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='name',
            field=models.CharField(default='aaa', max_length=200),
            preserve_default=False,
        ),
    ]
