# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-18 09:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_note_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_in_school', models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2)),
                ('name', models.CharField(max_length=30)),
                ('level_class', models.IntegerField()),
                ('phone_number', models.CharField(max_length=11)),
            ],
        ),
    ]
